apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1"
  storageClassName: "gluster-heketi-storageclass"
