apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: reids
      image: 10.4.60.235:5000/redis:v0.1  
      ports:
      - containerPort: 6379
      name: reid-access
      volumeMounts:
      - mountPath: "/data"
        name: redisdata
  volumes:
    - name: redisdata
      persistentVolumeClaim:
        claimName: redisdata
