apiVersion: v1
kind: Service
metadata:
  name: nginx-access-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - name: nginx-port
    protocol: "TCP"
    port: 30005
    nodePort: 30005
    targetPort: 
    
  selector:
    app: nginx
