apiVersion: v1
kind: Service
metadata:
  name: mongo-access-service
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
  - name: mongo-port
    protocol: "TCP"
    port: 27017
    nodePort: 30002
    targetPort: 27017
    
  selector:
    app: mongo
