apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
      - containerPort: 27017
      name: mongo-access
      volumeMounts:
      - mountPath: "/data/db"
        name: mongodata
  volumes:
    - name: mongodata
      persistentVolumeClaim:
        claimName: mongodata
