apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namesrvlogs
  namespace: rocketmq-operator
  
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "1"
  storageClassName: "gluster-heketi-storageclass"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namesrvstore
  namespace: rocketmq-operator
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "1"
  storageClassName: "gluster-heketi-storageclass"
