apiVersion: v1
kind: Service
metadata:
  name: mysql-controller
  labels:
    name: mysql-controller
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
