apiVersion: v1
kind: Service
metadata:
  name: redis-controller
  labels:
    name: redis-controller
spec:
  type: ClusterIP
  ports:
  - name: reids
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    appCluster: redis-cluster
