---
apiVersion: "rocketmq.huanwei.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : rocketmq-operator
spec:
  brokerImage: huanwei/rocketmq-broker-k8s:4.3.2
  nameServers: 10.4.60.161:9876;10.4.60.245:9876
  allMaster: true
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
  storageClassName: gluster-heketi-storageclass
